### PR TITLE
Update docs + loop unrolling

### PR DESCRIPTION
**Pull request by mike-barber**

### CODE REVIEW

**Comment by mike-barber** [comment]
@Kulasko I've found that it's possible to get a bit of extra perf out of unrolling the loops slightly. Given the complex pattern with skips etc, it looks like this doesn't happen automatically.

Are you happy with this going in with the idiomatic improvements?

**Review by Kulasko — COMMENTED** [review]
I see that you've added me as contributor, thanks :)

What about `FlagStorageBit Vector` and `FlagStorageByteVector`? I suppose their loops are simple enough for automatic unrolling? Did you try 4x unrolling, too?

**Comment by Kulasko** [comment]
Also, I generally have no problem with this going into the PR. It might be a bit less clean, but it saves a second PR, so it's fine in my book.

**Comment by mike-barber** [comment]
Thanks! I left the original bit vector alone, so there would be one straightforward one.

But then completely forgot about the byte vector :) I'll take a look at that when I get home.

I initially did 4x unrolling, but found 2x to be faster in both cases.

**Comment by mike-barber** [comment]
Hi @Kulasko there was a small performance benefit from unrolling the byte vector loop 4x, but not as large as one might expect: I guess it's fairly bandwidth heavy and light on compute. Slightly less benefit from 2x unrolling. I've left the 4x version in.

**Comment by Kulasko** [comment]
Looks good so far!
Most importantly, it does run pretty fast. The byte vector now manages almost 4500 passes on my machine and outperforms the bit vector by almost 5%. However, it seems a bit odd to me that you don't want to unroll the bit vector, which you recently mentioned as the main version for a comparison in the competition. Are you sure you want that?

**Comment by mike-barber** [comment]
Interesting, thanks! So the byte vector implementation sees a larger performance uplift on your machine; it's around 2% on mine. 

I should explain my reasoning for not unrolling the bit vector a bit better. I have 3 implementations that are eligible for the main competition. The original `FlagStorageBitVector` is the simplest and slowest of these. Since then I've added 
- `FlagStorageBitVectorRotate` which is identical except for a more efficient way to reset bits; and this has been adopted up by some of the C++ solutions too (https://github.com/PlummersSoftwareLLC/Primes/blob/drag-race/PrimeCPP/solution_1/PrimeCPP.cpp)
- `FlagStorageBitVectorStriped` with the different layout; it's not optimal, but it's really fast

Essentially, since we have two other bit storage solutions that are quite a bit faster than the original, we might as well leave the original one in a form that's easy to understand. Adding unrolling to it only gives us about 12.1k -> 12.8k.

**Review by Kulasko — APPROVED** [review]
Well, the byte vector was already faster than the bit vector on my machine, so it didn't change too much, but it is still interesting to see.

Interestingly, `FlagStorageBitVectorStriped` isn't too fast for me. The ceiling for each storage option on my machine are:
- 4500 for bytes
- 4300 for bits
- 4600 for bits-rotate
- 3300 for bits-striped

So in total, I think that betting on `FlagStorageBitVectorRotate` is the right thing to do, as it's the fastest on both of our machines.

**Comment by mike-barber** [comment]
Thanks for reviewing and approving!

I think bits-striped is probably slower on your machine because the dataset doesn't fit in the cache. The algorithm is pretty horrible from a locality perspective, but I can get away with it on the Ryzen.

**Pull request merged**
